name: Build Release

on: 
  workflow_dispatch:
      inputs:
        package-name:
          description: 'Name of the package to release'
          required: true
          type: choice
          options:
            - sh.orels.shaders
            - sh.orels.shaders.generator
            - sh.orels.shaders.inspector

jobs:

  pack-version:
    uses: ./.github/workflows/pack-package.yml
    with:
      package-name: ${{inputs.package-name}}

  update-release:
    needs: pack-version
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with: 
            path: "Packages/${{inputs.package-name}}/package.json"
            prop_path: "version"
            
      - name: Make Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          tag_name: "v${{ steps.version.outputs.prop }}"
          generate_release_notes: true
          draft: false

      - name: Make Pre-Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        if: startsWith(github.ref, 'refs/heads/dev')
        with:
          tag_name: "v${{ steps.version.outputs.prop }}"
          draft: false
          prerelease: true
          generate_release_notes: true

